[github]
token = "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"
owner = "polyesterschaf-png"
repo  = "Kalorik"
branch = "main"
base_path = "KalorikDaten"
committer_name  = "Kalorik App Bot"
committer_email = "kalorik-bot@example.org"
